[package]
name = "homebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = {version = "1.19", features = ["full"]}
serde_json = "1.0"
anyhow = "1.0"
serde = {version = "1.0.2", features = ["derive"]}
token-generator = "0.1.0"
actix-web = {version = "4", features = ["openssl"]}
openssl = "0.10"
toml = "0.7.1"